### ISSUE TITLE
Unknown token error when running test suite

### ISSUE THREAD

**Issue by kilahm** [HackPack/HackUnit#29]
This error occurs when attempting to run the entire suite:

```
$bin/hackunit test/ -e test/Fixtures/ -e test/Mocks/
Fatal error: Uncaught exception 'HH\InvariantException' with message 'Unknown class token 0' in /Users/isaacleinweber/personal/HackUnit/vendor/fredemmott/definition-finder/src/consumers/ClassConsumer.php:29
Stack trace:
#0 /Users/isaacleinweber/personal/HackUnit/vendor/fredemmott/definition-finder/src/consumers/ClassConsumer.php(29): HH\invariant_violation()
#1 /Users/isaacleinweber/personal/HackUnit/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(158): FredEmmott\DefinitionFinder\ClassConsumer->getBuilder()
#2 /Users/isaacleinweber/personal/HackUnit/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(126): FredEmmott\DefinitionFinder\ScopeConsumer->consumeDefinition()
#3 /Users/isaacleinweber/personal/HackUnit/vendor/fredemmott/definition-finder/src/consumers/ClassConsumer.php(83): FredEmmott\DefinitionFinder\ScopeConsumer->getBuilder()
#4 /Users/isaacleinweber/personal/HackUnit/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(158): FredEmmott\DefinitionFinder\ClassConsumer->getBuilder()
#5 /Users/isaacleinweber/personal/HackUnit/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(126): FredEmmott\DefinitionFinder\ScopeConsumer->consumeDefinition()
#6 /Users/isaacleinweber/personal/HackUnit/vendor/fredemmott/definition-finder/src/consumers/NamespaceConsumer.php(32): FredEmmott\DefinitionFinder\ScopeConsumer->getBuilder()
#7 /Users/isaacleinweber/personal/HackUnit/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(151): FredEmmott\DefinitionFinder\NamespaceConsumer->getBuilder()
#8 /Users/isaacleinweber/personal/HackUnit/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(126): FredEmmott\DefinitionFinder\ScopeConsumer->consumeDefinition()
#9 /Users/isaacleinweber/personal/HackUnit/vendor/fredemmott/definition-finder/src/FileParser.php(11): FredEmmott\DefinitionFinder\ScopeConsumer->getBuilder()
#10 /Users/isaacleinweber/personal/HackUnit/vendor/fredemmott/definition-finder/src/FileParser.php(31): FredEmmott\DefinitionFinder\FileParser->__construct()
#11 /Users/isaacleinweber/personal/HackUnit/vendor/fredemmott/definition-finder/src/FileParser.php(21): FredEmmott\DefinitionFinder\FileParser::FromData()
#12 /Users/isaacleinweber/personal/HackUnit/vendor/fredemmott/definition-finder/src/TreeParser.php(26): FredEmmott\DefinitionFinder\FileParser::FromFile()
#13 /Users/isaacleinweber/personal/HackUnit/vendor/fredemmott/definition-finder/src/TreeParser.php(36): FredEmmott\DefinitionFinder\TreeParser->__construct()
#14 /Users/isaacleinweber/personal/HackUnit/src/Test/Loader.php(57): FredEmmott\DefinitionFinder\TreeParser::FromPath()
#15 /Users/isaacleinweber/personal/HackUnit/src/HackUnit.php(54): HackPack\HackUnit\Test\Loader->testSuites()
#16 /Users/isaacleinweber/personal/HackUnit/bin/hackunit(22): HackPack\HackUnit\HackUnit::run()
#17 {main}
```

The file being parsed when the error occurs is currently unknown.  Token `0` has a name of `UNKNOWN`.

**Comment by kilahm** [comment]
This issue was fixed in https://github.com/fredemmott/definitions-finder/pull/8
