### ISSUE TITLE
Uncaught exception when test marked skipped

### ISSUE THREAD

**Issue by kilahm** [HackPack/HackUnit#34]
Marked a single test with `<<Test, Skip>>` and ran just that single file.

```
Fatal exception thrown in /Users/isaac_leinweber/personal/HackMini/vendor/hackpack/hackunit/src/Test/Runner.php on line 105.
Exception message:

Trace:
#0 /Users/isaac_leinweber/personal/HackMini/vendor/hackpack/hackunit/src/Assert.php(68): Closure$HackPack\HackUnit\Test\Runner::run#2()
#1 /Users/isaac_leinweber/personal/HackMini/vendor/hackpack/hackunit/src/Test/Suite.php(37): HackPack\HackUnit\Assert->skip()
#2 (): Closure$HackPack\HackUnit\Test\Suite::run#3()
#3 /Users/isaac_leinweber/personal/HackMini/vendor/hackpack/hackunit/src/Test/Suite.php(52): HH\Vector->map()
#4 /Users/isaac_leinweber/personal/HackMini/vendor/hackpack/hackunit/src/Test/Runner.php(123): HackPack\HackUnit\Test\Suite->run()
#5 (): Closure$HackPack\HackUnit\Test\Runner::run#4()
#6 /Users/isaac_leinweber/personal/HackMini/vendor/hackpack/hackunit/src/Test/Runner.php(127): HH\Vector->map()
#7 /Users/isaac_leinweber/personal/HackMini/vendor/hackpack/hackunit/src/HackUnit.php(52): HackPack\HackUnit\Test\Runner->run()
#8 /Users/isaac_leinweber/personal/HackMini/vendor/hackpack/hackunit/bin/hackunit(22): HackPack\HackUnit\HackUnit::run()
#9 {main}
```

**Comment by kilahm** [comment]
Runs fine with out the `Skip` annotation.
