### ISSUE TITLE
Error in use stament

### ISSUE THREAD

**Issue by guilhermegeek** [HackPack/HackUnit#38]
Happening in HHVM-3.14.0.0

Code Failling:

```php
use Test\Class1,
Test\Class2,
Test\Class3;
```
Error: 
```
Fatal error: Uncaught exception 'HH\InvariantException' with message 'Unexpected token ','' in /home/the-project/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php:320
Stack trace:
#0 /home/th-project/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(320): HH\invariant_violation()
#1 /home/th-project/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(82): FredEmmott\DefinitionFinder\ScopeConsumer->consumeUseStatement()
#2 /home/th-project/vendor/fredemmott/definition-finder/src/consumers/NamespaceConsumer.php(32): FredEmmott\DefinitionFinder\ScopeConsumer->getBuilder()
#3 /home/th-project/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(183): FredEmmott\DefinitionFinder\NamespaceConsumer->getBuilder()
#4 /home/th-project/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(156): FredEmmott\DefinitionFinder\ScopeConsumer->consumeDefinition()
#5 /home/th-project/vendor/fredemmott/definition-finder/src/FileParser.php(12): FredEmmott\DefinitionFinder\ScopeConsumer->getBuilder()
#6 /home/th-project/vendor/fredemmott/definition-finder/src/FileParser.php(38): FredEmmott\DefinitionFinder\FileParser->__construct()
#7 /home/th-project/vendor/fredemmott/definition-finder/src/FileParser.php(28): FredEmmott\DefinitionFinder\FileParser::FromData()
#8 /home/th-project/vendor/hackpack/hackunit/src/Test/SuiteBuilder.php(32): FredEmmott\DefinitionFinder\FileParser::FromFile()
#9 /home/th-project/vendor/hackpack/hackunit/src/HackUnit.php(23): HackPack\HackUnit\Test\SuiteBuilder->buildSuites()
#10 /home/th-project/vendor/hackpack/hackunit/src/Test/Loader.php(36): Closure$HackPack\HackUnit\HackUnit::run#2()
#11 /home/th-project/vendor/hackpack/hackunit/src/HackUnit.php(59): HackPack\HackUnit\Test\Loader->testSuites()
#12 /home/th-project/vendor/hackpack/hackunit/bin/hackunit(29): HackPack\HackUnit\HackUnit::run()
```

Code Working:

```php
use Test\Class1;
use Test\Class2;
use Test\Class3;`
```

**Comment by kilahm** [comment]
Thanks for finding this issue @guilhermegeek!  Unfortunately it's a problem with the parser in @fredemmott's library [hhvm-autoload](https://github.com/fredemmott/hhvm-autoload).  That library isn't all too complicated and Fred is very willing to accept pull requests.

I recently found another problem where the following wasn't parsing (even though it works in 3.13.1).

```php
<?hh // strict
use :x:doctype;
use :html;
```

I was planning on attempting to add support for xhp class use statements within the next couple of weeks, but if you would like to fix both issues please do!

**Comment by fredemmott** [comment]
Yep, you want to file those issues/send pull requests here: https://github.com/fredemmott/definition-finder/issues

**Comment by guilhermegeek** [comment]
Sorry my bad, i should noticed the log. 
I'll try to fix it. @fredemmott  if possible check my question about the failing test at https://github.com/fredemmott/definition-finder/issues/19.
